stages:
  - test
  - build_and_push
  - deploy

variables:
  IMAGE_NAME: registry.gitlab.com/samishafique786/aws-ci-cd
  DEPLOYMENT_FILE: eks-terraform/k8s/deployment.yaml
  K8S_NAMESPACE: default
  AWS_DEFAULT_REGION: eu-north-1

before_script:
  - echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY

# 1 Run unit tests first
test:
  stage: test
  image: python:3.9-slim
  before_script:
    - pip install --no-cache-dir -r hello-prometheus/requirements.txt
  script:
    - pytest hello-prometheus/test_app.py
  only:
    - main


# 2 Build and push Docker image in the same job
build_and_push:
  stage: build_and_push
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    # Login to GitLab Container Registry
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin registry.gitlab.com

    # Build Docker image with commit SHA tag
    - docker build -t $IMAGE_NAME:$CI_COMMIT_SHA hello-prometheus/
    - docker push $IMAGE_NAME:$CI_COMMIT_SHA

  only:
    - main

    # Tag as latest
    - docker tag $IMAGE_NAME:$CI_COMMIT_SHA $IMAGE_NAME:latest

deploy:
  stage: deploy
  image: ubuntu:22.04
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update && DEBIAN_FRONTEND=noninteractive TZ=UTC apt-get install -y awscli curl unzip sed
    - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    - chmod +x kubectl && mv kubectl /usr/local/bin/
  script:
    - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_DEFAULT_REGION
    - kubectl get nodes
    - kubectl get pods