stages:
  - build_and_push

variables:
  IMAGE_NAME: registry.gitlab.com/samishafique786/aws-ci-cd

build_and_push:
  stage: build_and_push
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin registry.gitlab.com
    - docker build -t $IMAGE_NAME:$CI_COMMIT_SHA hello-prometheus/
    - docker push $IMAGE_NAME:$CI_COMMIT_SHA
  only:
    - main
