global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # External Application Scrape Job
  - job_name: 'hello_world_app'
    static_configs:
      - targets: ['App to be deployed:5000']
