apiVersion: v1
kind: Service
metadata:
  name: nord-app-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-eip-allocations: "eipalloc-0641966eda840cc34"
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-03e5eeee21c4502a9"
spec:
  selector:
    app: nord-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer

